"""add_fields_for_risk_matrix

Revision ID: 0596080c4faf
Revises: a114b8b55409
Create Date: 2026-06-14 18:10:34.051002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0596080c4faf'
down_revision: Union[str, Sequence[str], None] = 'a114b8b55409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependencies', sa.Column('is_dev', sa.Boolean(), nullable=False))
    op.add_column('vulnerabilities', sa.Column('fixed_version', sa.String(length=100), nullable=True))
    op.add_column('vulnerabilities', sa.Column('exploit_available', sa.Boolean(), nullable=False))
    op.add_column('vulnerabilities', sa.Column('published_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'published_date')
    op.drop_column('vulnerabilities', 'exploit_available')
    op.drop_column('vulnerabilities', 'fixed_version')
    op.drop_column('dependencies', 'is_dev')
    # ### end Alembic commands ###
