"""add_indexes_on_foreign_keys

Revision ID: 230984a6b13e
Revises: 6a59f607026f
Create Date: 2026-08-16 00:20:03.393489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230984a6b13e'
down_revision: Union[str, Sequence[str], None] = '6a59f607026f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dependencies_analysis_id'), 'dependencies', ['analysis_id'], unique=False)
    op.drop_constraint(op.f('docker_results_analysis_id_key'), 'docker_results', type_='unique')
    op.create_index(op.f('ix_docker_results_analysis_id'), 'docker_results', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_recommendations_analysis_id'), 'recommendations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_dependency_id'), 'vulnerabilities', ['dependency_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_dependency_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_index(op.f('ix_recommendations_analysis_id'), table_name='recommendations')
    op.drop_index(op.f('ix_docker_results_analysis_id'), table_name='docker_results')
    op.create_unique_constraint(op.f('docker_results_analysis_id_key'), 'docker_results', ['analysis_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_dependencies_analysis_id'), table_name='dependencies')
    # ### end Alembic commands ###
