"""add_cve_service_version_and_truncation_fields

Revision ID: 2c95a3b3a49d
Revises: 7b0154a1219d
Create Date: 2026-07-05 15:17:46.380887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c95a3b3a49d'
down_revision: Union[str, Sequence[str], None] = '7b0154a1219d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('cve_service_version', sa.String(length=20), nullable=True))
    op.add_column('analyses', sa.Column('dependencies_truncated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('analyses', sa.Column('dependencies_scanned_count', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('dependencies_total_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'dependencies_total_count')
    op.drop_column('analyses', 'dependencies_scanned_count')
    op.drop_column('analyses', 'dependencies_truncated')
    op.drop_column('analyses', 'cve_service_version')
    # ### end Alembic commands ###
