"""add_scan_type_to_analysis

Revision ID: 4ccae846cc8f
Revises: 0596080c4faf
Create Date: 2026-06-14 18:27:14.857788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccae846cc8f'
down_revision: Union[str, Sequence[str], None] = '0596080c4faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('scan_type', sa.String(length=50), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'scan_type')
    # ### end Alembic commands ###
