"""Add cancel_requested and CANCELLED status

Revision ID: 53290224e098
Revises: 2c95a3b3a49d
Create Date: 2026-07-23 01:51:30.599474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53290224e098'
down_revision: Union[str, Sequence[str], None] = '2c95a3b3a49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False))
    
    # Ajout manuel pour PostgreSQL : ajouter la valeur à l'enum
    op.execute("ALTER TYPE analysisstatus ADD VALUE IF NOT EXISTS 'cancelled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'cancel_requested')
    # ### end Alembic commands ###
