"""add target_type to analysis

Revision ID: 7b0154a1219d
Revises: 4ccae846cc8f
Create Date: 2026-06-30 17:24:26.011103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0154a1219d'
down_revision: Union[str, Sequence[str], None] = '4ccae846cc8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('target_type', sa.String(length=50), server_default='github', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'target_type')
    # ### end Alembic commands ###
