"""Add coverage fields to analysis

Revision ID: 82516f80137e
Revises: d048b398b9b7
Create Date: 2026-07-25 15:29:34.198291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82516f80137e'
down_revision: Union[str, Sequence[str], None] = 'd048b398b9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('deps_detected', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('deps_analyzed', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('coverage_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'coverage_percent')
    op.drop_column('analyses', 'deps_analyzed')
    op.drop_column('analyses', 'deps_detected')
    # ### end Alembic commands ###
