"""create_all_tables

Revision ID: a114b8b55409
Revises: 
Create Date: 2026-06-09 19:31:15.463053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a114b8b55409'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('is_outdated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docker_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('base_image', sa.String(length=255), nullable=False),
    sa.Column('vulnerabilities_count', sa.Integer(), nullable=False),
    sa.Column('has_root_user', sa.Boolean(), nullable=False),
    sa.Column('image_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('DEPENDENCY', 'DOCKER', 'GLOBAL', name='targettype'), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'HTML', name='reportformat'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='severitylevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerabilities')
    op.drop_table('reports')
    op.drop_table('recommendations')
    op.drop_table('docker_results')
    op.drop_table('dependencies')
    op.drop_table('analyses')
    # ### end Alembic commands ###
