"""Add commit_sha and INCOMPLETE status

Revision ID: d048b398b9b7
Revises: 53290224e098
Create Date: 2026-07-25 15:24:51.619703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd048b398b9b7'
down_revision: Union[str, Sequence[str], None] = '53290224e098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('commit_sha', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'commit_sha')
    # ### end Alembic commands ###
